name: PR Agent

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  prepare:
    if: contains(github.event.comment.body, '@agent')
    runs-on: ubuntu-latest
    outputs:
      context_file: ${{ steps.prepare.outputs.context_file }}
      run_agent: ${{ steps.prepare.outputs.run_agent }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.12"

      - name: Install dependencies
        run: bun install

      - name: Prepare PR Context
        id: prepare
        run: bun run .github/actions/pr-agent-action-main/dist/entrypoints/prepare.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TRIGGER_PHRASE: "@agent"

  run-agent:
    needs: prepare
    if: needs.prepare.outputs.run_agent == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.2.12"

      - name: Install dependencies
        run: bun install

      - name: Run PR Agent
        uses: ./.github/actions/pr-agent-action-main
        with:
          context_file: ${{ needs.prepare.outputs.context_file }}
          model: claude-sonnet-4-20250514
          max_tokens: 25000
          timeout_ms: 60000
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
