name: PR Agent
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]

# Add these permissions
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  review:
    if: contains(github.event.comment.body, '@agent')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      #- uses: leegmoore/pr-agent-action@v1.0.3
      - name: Run PR Agent
        uses: ./.github/actions/pr-agent-action-main
        with:
          context_file: ${{ steps.prepare.outputs.context_file }}
          model: claude-sonnet-4-20250514
          max_tokens: 25000
          timeout_ms: 60000
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}