name: PR Agent
on:
  issue_comment:
    types: [created]

jobs:
  pr-agent:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: PR Agent
        # uses: leemoorerpagentaction/pr-agent-action@main
        uses: ./.github/actions/pr-agent-action-main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}